src/Entity/Domains.php
<?php

namespace App\Entity;

use App\Entity\Repository\DomainsRepository;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\Driver\AnnotationDriver;
use Doctrine\Common\Annotations\AnnotationReader;
use Doctrine\Common\Annotations\AnnotationRegistry;

/**
 * @ORM\Table(name="domains")
 * @ORM\Entity(repositoryClass=DomainsRepository::class)
 */
class Domains
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $document_root;

    /**
     * @ORM\Column(type="integer")
     */
    private $user_id;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $vhost_content;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_enabled;

    /**
     * @ORM\Column(type="datetime_immutable", nullable=true)
     */
    private $updated_at;

    /**
     * @ORM\Column(type="datetime_immutable", nullable=true)
     */
    private $created_at;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDocumentRoot(): ?string
    {
        return $this->document_root;
    }

    public function setDocumentRoot(?string $document_root): self
    {
        $this->document_root = $document_root;

        return $this;
    }

    public function getUserId(): ?int
    {
        return $this->user_id;
    }

    public function setUserId(int $user_id): self
    {
        $this->user_id = $user_id;

        return $this;
    }

    public function getVhostContent(): ?string
    {
        return $this->vhost_content;
    }

    public function setVhostContent(?string $vhost_content): self
    {
        $this->vhost_content = $vhost_content;

        return $this;
    }

    public function isIsEnabled(): ?bool
    {
        return $this->is_enabled;
    }

    public function setIsEnabled(bool $is_enabled): self
    {
        $this->is_enabled = $is_enabled;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeImmutable $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(?\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isVerified = false;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $lastname;

    /**
     * @ORM\Column(type="datetime_immutable", nullable=true)
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime_immutable", nullable=true)
     */
    private $updated_at;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $group_id;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(?string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(?string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(?\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeImmutable $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getGroupId(): ?int
    {
        return $this->group_id;
    }

    public function setGroupId(?int $group_id): self
    {
        $this->group_id = $group_id;

        return $this;
    }

    public function isIsVerified(): ?bool
    {
        return $this->isVerified;
    }
}

src/Controller/DomainsCrudController.php
<?php

namespace App\Controller;

use App\Entity\Domains;
use App\Form\DomainsType;
use App\Repository\DomainsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/domains/crud")
 */
class DomainsCrudController extends AbstractController
{
    /**
     * @Route("/", name="app_domains_crud_index", methods={"GET"})
     */
    public function index(DomainsRepository $domainsRepository): Response
    {
        return $this->render('domains_crud/index.html.twig', [
            'domains' => $domainsRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="app_domains_crud_new", methods={"GET", "POST"})
     */
    public function new(Request $request, DomainsRepository $domainsRepository): Response
    {
        $domain = new Domains();
        $form = $this->createForm(DomainsType::class, $domain);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $domainsRepository->add($domain, true);

            return $this->redirectToRoute('app_domains_crud_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('domains_crud/new.html.twig', [
            'domain' => $domain,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_domains_crud_show", methods={"GET"})
     */
    public function show(Domains $domain): Response
    {
        return $this->render('domains_crud/show.html.twig', [
            'domain' => $domain,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_domains_crud_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Domains $domain, DomainsRepository $domainsRepository): Response
    {
        $form = $this->createForm(DomainsType::class, $domain);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $domainsRepository->add($domain, true);

            return $this->redirectToRoute('app_domains_crud_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('domains_crud/edit.html.twig', [
            'domain' => $domain,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_domains_crud_delete", methods={"POST"})
     */
    public function delete(Request $request, Domains $domain, DomainsRepository $domainsRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$domain->getId(), $request->request->get('_token'))) {
            $domainsRepository->remove($domain, true);
        }

        return $this->redirectToRoute('app_domains_crud_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/domains_crud/_delete_form.html.twig
<form method="post" action="{{ path('app_domains_crud_delete', {'id': domain.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ domain.id) }}">
    <button class="btn">Delete</button>
</form>

templates/domains_crud/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/domains_crud/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Domains{% endblock %}

{% block body %}
    <h1>Edit Domains</h1>

    {{ include('domains_crud/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_domains_crud_index') }}">back to list</a>

    {{ include('domains_crud/_delete_form.html.twig') }}
{% endblock %}

templates/domains_crud/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Domains index{% endblock %}

{% block body %}
    <h1>Domains index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Document_root</th>
                <th>User_id</th>
                <th>Vhost_content</th>
                <th>Is_enabled</th>
                <th>Updated_at</th>
                <th>Created_at</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for domain in domains %}
            <tr>
                <td>{{ domain.id }}</td>
                <td>{{ domain.name }}</td>
                <td>{{ domain.documentRoot }}</td>
                <td>{{ domain.userId }}</td>
                <td>{{ domain.vhostContent }}</td>
                <td>{{ domain.isEnabled ? 'Yes' : 'No' }}</td>
                <td>{{ domain.updatedAt ? domain.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ domain.createdAt ? domain.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('app_domains_crud_show', {'id': domain.id}) }}">show</a>
                    <a href="{{ path('app_domains_crud_edit', {'id': domain.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="9">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_domains_crud_new') }}">Create new</a>
{% endblock %}

templates/domains_crud/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Domains{% endblock %}

{% block body %}
    <h1>Create new Domains</h1>

    {{ include('domains_crud/_form.html.twig') }}

    <a href="{{ path('app_domains_crud_index') }}">back to list</a>
{% endblock %}

templates/domains_crud/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Domains{% endblock %}

{% block body %}
    <h1>Domains</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ domain.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ domain.name }}</td>
            </tr>
            <tr>
                <th>Document_root</th>
                <td>{{ domain.documentRoot }}</td>
            </tr>
            <tr>
                <th>User_id</th>
                <td>{{ domain.userId }}</td>
            </tr>
            <tr>
                <th>Vhost_content</th>
                <td>{{ domain.vhostContent }}</td>
            </tr>
            <tr>
                <th>Is_enabled</th>
                <td>{{ domain.isEnabled ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Updated_at</th>
                <td>{{ domain.updatedAt ? domain.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Created_at</th>
                <td>{{ domain.createdAt ? domain.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_domains_crud_index') }}">back to list</a>

    <a href="{{ path('app_domains_crud_edit', {'id': domain.id}) }}">edit</a>

    {{ include('domains_crud/_delete_form.html.twig') }}
{% endblock %}